del chips\*.png
del chipshist\*.png
del dilates\*.png
del dnnsIn\*.png
del dnnsOut\*.png
del dnnsHisteq\*.png
del facades\*.png
del facadeshist\*.png
del aligns\*.png
del segs\*.png
del resizes\*.png
del invalid_facades\*.png
del invalid_facadesHisteq\*.png
del score.txt
del confidence.txt
del index.html